#!/bin/bash

# AWS Practitioner Teacher - Deployment Script

echo "🚀 AWS Practitioner Teacher - Deployment Guide"
echo "================================================"
echo ""

echo "📋 Your website is ready to be published!"
echo ""
echo "Choose one of the following deployment methods:"
echo ""

echo "1️⃣  GitHub Pages (Recommended - Free)"
echo "   Steps:"
echo "   • Go to https://github.com/new"
echo "   • Repository name: AWS-Practitioner-Teacher"
echo "   • Make it Public"
echo "   • DO NOT initialize with README"
echo "   • Click 'Create repository'"
echo "   • Then run these commands:"
echo ""
echo "   git remote add origin https://github.com/YOUR-USERNAME/AWS-Practitioner-Teacher.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "   • Go to repository Settings → Pages"
echo "   • Source: Deploy from branch 'main'"
echo "   • Save"
echo "   • Your site will be live at: https://YOUR-USERNAME.github.io/AWS-Practitioner-Teacher/"
echo ""

echo "2️⃣  Netlify (Easiest - Free)"
echo "   Steps:"
echo "   • Go to https://app.netlify.com/drop"
echo "   • Drag and drop this entire folder"
echo "   • Your site will be live instantly!"
echo "   • You can customize the URL in site settings"
echo ""

echo "3️⃣  Vercel (Free)"
echo "   Steps:"
echo "   • Go to https://vercel.com/new"
echo "   • Import your GitHub repository (after pushing to GitHub)"
echo "   • Click Deploy"
echo "   • Your site will be live instantly!"
echo ""

echo "4️⃣  Local Testing"
echo "   Already opened in your browser!"
echo "   Or run: python3 -m http.server 8000"
echo "   Then visit: http://localhost:8000"
echo ""

echo "✅ Repository is initialized and committed!"
echo "📁 All files are ready in: $(pwd)"
echo ""
echo "📱 The website is mobile-responsive and works on all devices!"
echo ""
